FROM ruby:2.5
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    node.js \
    postgresql-client \
    yarn
WORKDIR /product-register
COPY Gemfile Gemfile.lock /product-register/
RUN bundle install 
#&& bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
COPY . .
CMD ["rails","s"]
